Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ${ec2_image_id} # Amazon Linux 2 AMI
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install Docker
          sudo yum update -y
          sudo yum install -y docker git
          sudo service docker start
          # Pull and run Docker container
          sudo docker run -d -p 80:${inner_port} -e DB_HOST=${db_endpoint} -e DB_USER=${db_user} -e DB_PASSWORD=${db_password} ${docker_image}

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access to the instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
